[package]
name = "reqcoon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
enum-iterator = "1.5.0"
http = "1.0.0"
json = "0.12.4"
log = "0.4"
nonempty = "0.10.0"
ratatui = "0.26.0"
reqwest = { version = "0.11", features = ["blocking"] }
simple-logging = "2.0"
textwrap = "0.16.1"
tui-input = "0.8.0"
